[package]
name = "vocab"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12", features = ["tokio"] }
tokio = { version = "1.36", features = ["fs", "rt"] }
rfd = "0.14"
json = "0.12.4"
