[package]
name = "vocab"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
iced = { version = "0.12", features = ["tokio", "advanced"] }
tokio = { version = "1.36", features = ["rt"] }
rfd = "0.14"
json = "0.12.4"
async-std = "1.12"

[target.'cfg(target_family = "wasm")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tokio = { version = "1.36", features = ["fs"] }
